### PR TITLE
Add free format encoding

### PR DESCRIPTION
**Pull request by eblanca**
A very few modifications allow for encoding in MPEG1/2 free format also.
I did some tests encoding in both MPEG1 and 2, with and without padding, with and without crc protection and everything seems to be working fine.

### CODE REVIEW

**Comment by eblanca** [comment]
I just noticed my text editor removed a lot of trailing white spaces, so the modifications appear many more than they really are. Sorry for this.

**Comment by njh** [comment]
Which players have you tested against?

Would be good to fix Line-endings but would be good to put them in a different commit.

**Comment by eblanca** [comment]
I trust both madplay and mpg123 for decoding audio mpeg files (more on the former).

**Comment by eblanca** [comment]
I updated frontend.c setting back those trailing white spaces.

**Comment by njh** [comment]
Had to merge manually

**Pull request merged**
